"""Add RAG system tables for documents, chunks, embeddings and queries

Revision ID: 8a2ecc16f2dd
Revises: 3ec070505365
Create Date: 2025-08-07 17:31:19.140098

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a2ecc16f2dd"
down_revision: Union[str, None] = "3ec070505365"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
